# Generates Injector/EmbeddedDll.h from a built Osiris.dll.
# Used by build_injector.ps1 (local) and by the GitHub Actions workflow.
param(
    [ValidateSet('Release', 'Debug')]
    [string]$Configuration = 'Release',
    [string]$DllPath = '',
    [string]$HeaderPath = ''
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$repo = Split-Path -Parent $root

if (-not $DllPath)   { $DllPath = Join-Path $repo "x64\$Configuration\Osiris.dll" }
if (-not $HeaderPath) { $HeaderPath = Join-Path $root 'EmbeddedDll.h' }

if (-not (Test-Path $DllPath)) {
    Write-Output "WARN: $DllPath not found; generating empty embedded DLL header"
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine('// Generated by generate_embedded.ps1 - do not edit manually.')
    [void]$sb.AppendLine('#pragma once')
    [void]$sb.AppendLine('static const unsigned char kEmbeddedDll[] = {0};')
    [void]$sb.AppendLine('static const unsigned int kEmbeddedDllSize = 0;')
    [System.IO.File]::WriteAllText($HeaderPath, $sb.ToString())
    exit 0
}

$bytes = [System.IO.File]::ReadAllBytes($DllPath)

$sb = New-Object System.Text.StringBuilder(($bytes.Length * 6) + 256)
[void]$sb.AppendLine('// Generated by generate_embedded.ps1 - do not edit manually.')
[void]$sb.AppendLine('#pragma once')
[void]$sb.AppendLine('static const unsigned char kEmbeddedDll[] = {')

$line = New-Object System.Text.StringBuilder(384)
foreach ($b in $bytes) {
    [void]$line.Append('0x')
    [void]$line.Append($b.ToString('x2'))
    [void]$line.Append(',')
    if ($line.Length -ge 150) {
        [void]$sb.AppendLine($line.ToString())
        $null = $line.Clear()
    }
}
if ($line.Length -gt 0) {
    [void]$sb.AppendLine($line.ToString())
}

[void]$sb.AppendLine('};')
[void]$sb.AppendLine("static const unsigned int kEmbeddedDllSize = $($bytes.Length);")
[System.IO.File]::WriteAllText($HeaderPath, $sb.ToString())
Write-Output "OK: embedded $($bytes.Length) bytes from $DllPath -> $HeaderPath"
