# Generates the injector resource script at build time.
# Invoked by a custom command in Injector/CMakeLists.txt with:
#   -DICON_PATH=<absolute path to Injector.ico>
#   -DDLL_PATH=<absolute path to the freshly built Osiris.dll>
#   -DMANIFEST_PATH=<absolute path to Injector.manifest>  (GNU/MinGW only)
#   -DOUTPUT=<absolute path of the .rc file to write>
#
# All paths are normalized to forward slashes so both rc.exe (MSVC/clang-cl)
# and windres (MinGW) accept them. No byte transformation happens here: the
# resource compiler embeds Osiris.dll verbatim as RCDATA at link time.
if(NOT DEFINED OUTPUT OR NOT DEFINED DLL_PATH)
  message(FATAL_ERROR "OUTPUT and DLL_PATH are required")
endif()

file(TO_CMAKE_PATH "${ICON_PATH}" icon_path)
file(TO_CMAKE_PATH "${DLL_PATH}" dll_path)

set(content "// Generated by make_embedded_rc.cmake - do not edit.\n")
string(APPEND content "#define IDR_EMBEDDED_DLL 101\n")
string(APPEND content "IDI_ICON1 ICON \"${icon_path}\"\n")
string(APPEND content "IDR_EMBEDDED_DLL RCDATA \"${dll_path}\"\n")
if(DEFINED MANIFEST_PATH AND NOT MANIFEST_PATH STREQUAL "")
  file(TO_CMAKE_PATH "${MANIFEST_PATH}" manifest_path)
  string(APPEND content "1 RT_MANIFEST \"${manifest_path}\"\n")
endif()

file(WRITE "${OUTPUT}" "${content}")
